### ISSUE TITLE
Equality operator (==) causes exception on custom delegates

### ISSUE THREAD

**Issue by GWBasic** [adrianoc/cecilifier#113]
The following code doesn't work. I suspect the problem is accessing the static field myDelegate.

If I comment out My's contents and just return null, the code compiles and I get Cecil.

(Awesome tool, BTW. So far this is the greatest learning resource I've found for Cecil.)

`
 using System;

 namespace MakeADelegate
 {
	public delegate object MyDelegate(string arg);

	public static class ObjectMaker
	{
		public static MyDelegate myDelegate = null;

		public static object My(string arg)
		{
			if (ObjectMaker.myDelegate == null)
			{
				throw new Exception($"Can't construct a mock XXX: YYY.ZZZ is null");
			}

			return myDelegate(arg);
		}
	}
 }
`

**Comment by adrianoc** [comment]
HI @GWBasic. 

> Something went wrong. Please report the following error in the google group or in the git repository: System.ArgumentException: Could not find variable declaration for method op_Equality. at Cecilifier.Core.Extensions.MethodExtensions.MethodResolverExpression(IMethodSymbol method, IVisitorContext ctx) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/Extensions/MethodExtensions.cs:line 40

Is this the exception you are getting ?

> (Awesome tool, BTW. So far this is the greatest learning resource I've found for Cecil.)

Thanks, that is my goal :).. make it easier for devs to get used to Mono.Cecil  / IL

**Comment by GWBasic** [comment]
Exactly!

BTW, I can kind-of work around the bug with the code pasted below. The resulting cecil calls have lots of "not supported" comments, though.

using System;

namespace MakeADelegate
{
	public delegate object MyDelegate(string arg);

	public static class ObjectMaker
	{
		public static MyDelegate myDelegate = null;

		public static object My(string arg)
		{
			if (ObjectMaker.myDelegate is null)
			{
				throw new Exception($"Can't construct a mock XXX: YYY.ZZZ is null");
			}

			return ObjectMaker.myDelegate.Invoke(arg);
		}
	}
}

**Comment by adrianoc** [comment]
Indeed.

I think it makes sense to add support for ThrowStatement. Actually it would be pretty easy.


`IsPatternExpression`, i.e, 

```CSharp
if (ObjectMaker.myDelegate is null)
```

should also not be hard to add

**Comment by adrianoc** [comment]
just filled 2 issues:

https://github.com/adrianoc/cecilifier/issues/114
https://github.com/adrianoc/cecilifier/issues/115
