### ISSUE TITLE
Generated assembly is missing entry point

### ISSUE THREAD

**Issue by RenanPeruscello** [adrianoc/cecilifier#38]
We should detect whether the generated assembly contains a *Main* method with a signature matching *static void Main(string[])* and set that as the assembly entry point.

Example: https://cecilifier.me/?gistid=a9f6210e44886d2bd6af59a8565e09ab

**Comment by adrianoc** [comment]
Fixed in f39eb7fc709a104df65adffda27258e56693c8ab
